### PR TITLE
upgraded to triangle/v2

### PR DESCRIPTION
**Pull request by esimov**
With triangle/v2 you need to include some additional parameters into the `Processor` struct and it should work. The `Processor` struct initialization should look something like this:

```go
return &showerglass.Processor{
	MaxPoints:  1500,
	BlurRadius: 4,
	BlurFactor: 1,
	EdgeFactor: 6,
	PointRate:  0.075,
}
```

I have deleted also the `go.mod` from the core folder, it's not really needed.

### CODE REVIEW

**Comment by pjebs** [comment]
I copied your approach from `pigo` where you have a `core` directory with the actual package inside.

That actually requires a separate `go.mod` inside the core directory, because when you import it, go just assumes it _is_ the package and is not necessarily a sub-package of a parent package. Go won't search for the parent package, therefore it won't find the outer `go.mod` file. `go get` will then simply use the latest versions of each dependency package - which may not be what you intended.

You can also tag the inner package separately to the outer package like this: https://github.com/golang/go/issues/52177

**Comment by esimov** [comment]
So you intended to decouple the core package from the cli application and to give the possibility of the users to download only the core part. If that was your intention it makes sanse. I will update it soon.

**Comment by pjebs** [comment]
In your case you have a CLI. In my case I have a demo project. They should not be importable by others.

**Comment by pjebs** [comment]
Thank you for your awesome contribution. My repo is now "complete" and tagged v1.0.0

**Comment by esimov** [comment]
> Thank you for your awesome contribution. My repo is now "complete" and tagged v1.0.0

It's my pleasure. You gave me a few ideas how could I update my WASM real time demos using Pigo.

**Comment by pjebs** [comment]
What's the plan with pigo project?

**Comment by esimov** [comment]
> What's the plan with pigo project?

What do you mean? You are referring to the current status of the project development or what?

**Comment by pjebs** [comment]
You implied you have something special for the WASM pigo project. I was just curious what it was.

**Comment by esimov** [comment]
Yes, there is this Github project https://github.com/esimov/pigo-wasm-demos exposing some WASM based demos using Pigo. There is also a demo using the Triangle package, but comparing to this project is a bit awkward. So I wish to adjust a little bit to make it much nicer.

**Comment by pjebs** [comment]
I had a look at the code. I could not follow along.

**Comment by esimov** [comment]
No problem, I will keep you updated once I'm done with it.

**Comment by esimov** [comment]
Hey, as a follow up I have completely rewritten the demos which I have been referred to earlier so you might check it out here if you are interested: https://github.com/esimov/pigo-wasm-demos.

**Comment by pjebs** [comment]
Looks more awesome now

**Pull request closed without merging**
